import { notFound } from "next/navigation";
import { ArticleDocument, ArticleSection } from "@/app/components/ArticleDocument";
import { ResearchShell } from "@/app/components/ResearchShell";

const articles: Record<string, { kind: string; title: string; dek: string; publishedAt: string; updatedAt: string; status: string; sourceFile?: string; sourceDescription?: string; sections?: Array<[string, string]> }> = {
  "daily-a-share-report-20260903": { kind: "交易研究 / 每日综合", title: "每日A股综合报告：2026年9月3日", dek: "Hermes每日综合报告，汇总市场温度、板块、策略、持仓与作战计划。", publishedAt: "2026-09-03", updatedAt: "2026-09-03", status: "已发布 · Hermes报告；数据截至2026-09-03", sourceFile: "daily-a-share-report-20260903.html", sourceDescription: "Hermes每日A股综合报告原文。发布适配仅清理了明细表中的完全重复行，并校正了表格数量标注；报告正文的市场数据、判断、持仓与作战计划保持原样。" },
  "temperature-gated-mechanism-20260903": { kind: "研究机制 / 温度门控", title: "温度门控决策机制：从市场温度到投资方案", dek: "市场温度五档→门控选策略→多策略共振加权→质量核验→仓位熔断的完整决策流水线，附9月3日运行版。", publishedAt: "2026-09-03", updatedAt: "2026-09-03", status: "已发布 · 运行于2026-09-03，数据截至2026-09-03", sourceFile: "temperature-gated-mechanism-20260903.html", sourceDescription: "温度门控机制运行版：展示市场温度档位、门控策略白名单、熔断状态与共振候选（9月3日候选为空＝偏冷档fail-safe的诚实表现）。机制为研究/决策建议层，非自动下单，不构成投资建议；未接入熔断项（组合回撤/破位联动等）需人工配合执行。" },
  "market-temperature-thermometer-20260903": { kind: "板块研究 / 市场温度", title: "市场温度计：9月3日运行版（数据截至9月2日）", dek: "用最新可用的申万二级行业和同花顺核心主题指数观察市场温度、升温变化与板块分布。", publishedAt: "2026-09-03", updatedAt: "2026-09-03", status: "已发布 · 运行于2026-09-03，行业/主题数据截至2026-09-02", sourceFile: "market-temperature-thermometer-20260903.html", sourceDescription: "本页于2026-09-03运行温度计流程；由于申万行业指数和同花顺主题指数当时均未更新至2026-09-03，正文实际数据截至2026-09-02。温度是相对热度监测，不构成实时交易指令。" },
  "market-temperature-thermometer-20260902": { kind: "板块研究 / 市场温度", title: "市场温度计：板块热度、升温变化与四象限分布", dek: "用申万二级行业和同花顺核心主题观察市场温度、三日升温速度与全部板块的象限位置。", publishedAt: "2026-09-02", updatedAt: "2026-09-02", status: "已发布 · 行业截至2026-09-02，主题截至2026-09-01", sourceFile: "market-temperature-thermometer-20260902.html", sourceDescription: "正文为温度计研究产物；申万行业指数截至2026-09-02，同花顺主题指数截至2026-09-01。页面中的温度是相对热度监测，不构成实时交易指令。" },
  "20260830-value-logic-full-research-v3": { kind: "价值逻辑 / 三周期作战", title: "价值逻辑分析报告：36项逻辑全量研究与三周期作战计划", dek: "基于真实需求、产业价值点、公司利润、估值位置和催化验证，整理36项价值逻辑，并给出长线、中线、短线的下周行动边界。", publishedAt: "2026-08-30", updatedAt: "2026-08-30", status: "已发布 · 数据截至2026-08-28", sourceFile: "20260830-value-logic-full-research-v3.html" },
  "20260828-optical-interconnect-panorama": { kind: "板块研究 / 光互连", title: "光互连技术路线全景研究", dek: "从SK海力士一篇论文，到AI光互联的产业链重构：技术路线谱系、产业链映射、价值迁移与跟踪指标。", publishedAt: "2026-08-28", updatedAt: "2026-08-28", status: "已发布", sourceFile: "20260828-optical-interconnect-panorama.html" },
  "ai-panorama-six-lines-20260823": { kind: "板块研究 / AI科技", title: "AI科技板块产业链总图（六线总纲）", dek: "从产业链、利润池、技术代际和六条投资线建立AI科技研究总图。", publishedAt: "2026-08-23", updatedAt: "2026-08-23", status: "已发布 · 数据截至2026-08-21", sourceFile: "ai-panorama-six-lines-20260823.html" },
  "ai-interconnect-investment-20260823": { kind: "专题研究 / 互联线", title: "AI互联线投资研究报告", dek: "从光模块、光芯片、交换设备、光纤铜缆到网络服务，梳理互联线的需求、技术和代表公司。", publishedAt: "2026-08-23", updatedAt: "2026-08-23", status: "已发布 · 数据截至2026-08-21", sourceFile: "ai-interconnect-investment-20260823.html" },
  "optical-module-thermal-investment-20260823": { kind: "专题研究 / 光模块散热", title: "光模块散热赛道投资研究报告", dek: "围绕高功耗光模块、液冷、导热材料与陶瓷封装，梳理赛道与代表公司。", publishedAt: "2026-08-23", updatedAt: "2026-08-23", status: "已发布 · 数据截至2026-08-21", sourceFile: "optical-module-thermal-investment-20260823.html" },
  "ai-interconnect-20260823": { kind: "专题研究 / 互联线", title: "AI互联线：从材料、光芯片到集群网络", dek: "互联不是单一的光模块行情，而是连接芯片、服务器、交换机和数据中心的系统工程。", publishedAt: "2026-08-23", updatedAt: "2026-08-23", status: "已发布 · 继续维护", sections: [["先看需求", "AI集群规模扩大后，算力芯片之间、服务器之间和机柜之间的数据交换成为瓶颈。互联带宽、时延、功耗和可靠性决定集群的有效利用率。"], ["产业链结构", "上游是磷化铟、硅光材料和封装材料；中游是激光器、探测器、光引擎、光器件和光模块；下游是交换机、光纤连接和集群网络。铜互联、硅光、薄膜铌酸锂等路线需要分别判断成熟度和商业化位置。"], ["投资研究边界", "光模块龙头的高景气并不等于所有互联标的都具备同样弹性。后续专题重点核对客户验证、产品代际、量产节奏、毛利率和资本开支，而不是只按概念映射。"]] },
  "20260822-ai-industry-value-chain-panorama-v3.html": { kind: "板块研究 / AI科技", title: "AI全产业链分层详解", dek: "以六条主线组织AI产业：算力线、存储线、互联线、供电线、应用线、承载线。", publishedAt: "2026-08-22", updatedAt: "2026-08-23", status: "已发布 · 版本维护", sections: [["六条主线", "算力线解决计算，存储线解决数据保存与搬运，互联线解决节点连接，供电线解决电能转换与热管理，应用线把模型能力转成用户价值，承载线提供机房、网络和运维环境。"], ["从原材料到应用", "研究顺序沿制造端向上拆解，也沿需求端向下验证：材料和设备必须最终映射到可交付的服务器、集群、模型服务或行业应用，不能停在概念名称。"], ["盈利观察", "高议价环节通常具有生态、认证、工艺或客户粘性；标准化组装和单纯扩产环节竞争更激烈。利润判断需要结合产品结构、客户集中度、资本开支和现金流。"]] },
  "ai-hardware-value-chain-20260822": { kind: "专题研究 / 硬件价值链", title: "AI硬件价值链：服务器、互联与供电散热", dek: "从终端要用上AI算力的需求出发，反推服务器、存储、网络、供电、散热和机房的采购关系。", publishedAt: "2026-08-22", updatedAt: "2026-08-23", status: "已发布 · 继续维护", sections: [["终端采购逻辑", "终端通常采购整机服务器、整柜系统或云算力服务，而不是从单一材料端开始。服务器之外还需要网络、存储、供配电、散热、机房和运维。"], ["关键价值点", "加速芯片、先进封装、高带宽存储、高速互联、液冷和高可靠供电共同决定系统性能；但不同客户的架构会改变BOM和利润分配，不能简单把所有上游都等同于英伟达路线。"], ["后续研究", "下一步按板块、专题和个股建立研究卡片：需求、技术路线、客户验证、竞争格局、财务兑现、估值位置和风险事件。"]] },
};

export function generateStaticParams() { return Object.keys(articles).map((slug) => ({ slug })); }

export default async function ReportDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = articles[slug];
  if (!article) notFound();
  if (article.sourceFile) {
    return <ResearchShell eyebrow="RESEARCH LIBRARY / PUBLISHED REPORT" title={article.title} description={article.sourceDescription ?? "正文保留原研究报告结构；研究参考，不构成实时交易指令。"}><div className="published-report-shell"><iframe className="published-report-frame" title={article.title} src={`/reports/source/${article.sourceFile}`} /></div></ResearchShell>;
  }
  return <ResearchShell eyebrow="RESEARCH LIBRARY / ARTICLE" title="文章阅读" description="研究成果页面；正文是可读发布层，数据与证据仍以本地研究产物为准。"><ArticleDocument kind={article.kind} title={article.title} dek={article.dek} publishedAt={article.publishedAt} updatedAt={article.updatedAt} status={article.status}>{article.sections?.map(([title, body]) => <ArticleSection title={title} key={title}><p>{body}</p></ArticleSection>)}</ArticleDocument></ResearchShell>;
}
