import Link from "next/link";
import { ResearchShell } from "@/app/components/ResearchShell";
import moduleIndex from "@/content/research/modules/index.json";
import economics from "@/content/research/economics/ai-module-economics-v1.json";
import { reportsForModule } from "@/app/lib/publishedReports";

export function generateStaticParams() { return moduleIndex.items.map((item) => ({ slug: item.id })); }

export default async function ModuleDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = moduleIndex.items.find((module) => module.id === slug);
  if (!item) return null;
  const economicsItem = economics.modules.find((module) => module.id === slug);
  return <ResearchShell eyebrow={`02 / VALUE MODULE / ${item.id}`} title={item.name} description={item.short}>
    <div className="mt-4 flex flex-wrap gap-3 text-xs"><Link href="/themes/ai-technology" className="text-[var(--accent-dark)]">← 返回AI全景图</Link><Link href="/topics" className="text-[var(--accent-dark)]">专题队列 →</Link></div>
    <section className="mt-6 grid gap-3 md:grid-cols-2"><article className="dashboard-panel"><p className="section-label">DEMAND PATH</p><h2 className="mt-2 text-lg font-semibold">需求逻辑</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{item.demandPath}</p></article><article className="dashboard-panel"><p className="section-label">MANUFACTURING PATH</p><h2 className="mt-2 text-lg font-semibold">制造逻辑</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{item.manufacturingPath}</p></article></section>
    <section className="mt-4 dashboard-panel"><p className="section-label">CURRENT BOTTLENECK</p><h2 className="mt-2 text-lg font-semibold">价值兑现的关键约束</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{item.bottleneck}</p></section>
    <section className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">REPRESENTATIVE COMPANIES</p><h2>龙头与代表公司观察位</h2></div><span className="text-xs text-[var(--muted)]">产业映射，非买入建议</span></div><div className="mt-4 grid gap-2 md:grid-cols-2">{item.representatives?.map((company) => <div key={company} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3 text-xs leading-5">{company}</div>)}</div><p className="mt-4 text-xs leading-6 text-[var(--muted)]">代表公司用于建立研究坐标。进入个股档案前，仍需核对实际产品、收入占比、客户、公告时点、估值和当前位置。</p></section>
    {reportsForModule[slug]?.length ? <section className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">已发布研究 / 模块文章</p><h2>从模块进入专题正文</h2></div><Link href="/reports" className="text-xs font-semibold text-[var(--accent-dark)]">文章总表 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{reportsForModule[slug].map((report) => <Link key={report.slug} href={`/reports/${report.slug}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><p className="text-sm font-semibold">{report.title} →</p><p className="mt-2 text-xs leading-5 text-[var(--secondary)]">{report.summary}</p></Link>)}</div></section> : null}
    {economicsItem && <section className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">ECONOMICS / QDH SNAPSHOT</p><h2>收入、成本与利润结果</h2></div><span className="text-xs text-[var(--muted)]">截至 {economics.as_of_date} · {economics.release_id}</span></div><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{economicsItem.initial.valuePoint}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="border border-[var(--line)] p-3 text-xs leading-6"><b>经济性判断：</b>{economicsItem.initial.profitProfile}<br/><b>收入来源：</b>{economicsItem.initial.revenueModel}<br/><b>主要成本：</b>{economicsItem.initial.majorCosts}</div><div className="border border-[var(--line)] p-3 text-xs leading-6"><b>资本强度：</b>{economicsItem.initial.capexIntensity}<br/><b>现金流风险：</b>{economicsItem.initial.cashFlowRisk}<br/><b>议价权：</b>{economicsItem.initial.pricingPower}</div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[860px] text-left text-xs"><thead><tr className="border-b border-[var(--line)]"><th className="p-2">公司</th><th className="p-2">财报期</th><th className="p-2">收入</th><th className="p-2">净利润</th><th className="p-2">毛利率</th><th className="p-2">收入同比</th><th className="p-2">PE-TTM</th><th className="p-2">经营现金流</th></tr></thead><tbody>{economicsItem.companies.filter((company) => company.market.close !== null).map((company) => <tr key={company.symbol} className="border-b border-[var(--line)]"><td className="p-2 font-medium">{company.name} <span className="text-[var(--muted)]">{company.symbol}</span></td><td className="p-2">{company.latest_filing.end_date ?? "—"}</td><td className="p-2">{company.income.revenue === null ? "—" : (company.income.revenue / 100000000).toFixed(2) + "亿"}</td><td className="p-2">{company.income.net_income_attr === null ? "—" : (company.income.net_income_attr / 100000000).toFixed(2) + "亿"}</td><td className="p-2">{company.quality.gross_margin_pct === null ? "—" : company.quality.gross_margin_pct.toFixed(1) + "%"}</td><td className="p-2">{company.quality.revenue_yoy_pct === null ? "—" : company.quality.revenue_yoy_pct.toFixed(1) + "%"}</td><td className="p-2">{company.market.pe_ttm === null ? "—" : company.market.pe_ttm.toFixed(1)}</td><td className="p-2">{company.cashflow.operating_cashflow === null ? "—" : (company.cashflow.operating_cashflow / 100000000).toFixed(2) + "亿"}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-6 text-[var(--muted)]">这是QDH财务和估值截面，不等于买入建议；分部收入、客户认证、产品路线和订单质量仍需专题级核验。</p></section>}
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">TOPIC SEEDS</p><h2>专题入口</h2></div><span className="research-tag">待研究</span></div><div className="mt-4 grid gap-3 md:grid-cols-3">{item.topics.map((topic) => <Link key={topic} href={`/topics/${topic}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-2"><p className="section-label">TOPIC</p><span className="research-tag">待研究</span></div><h3 className="mt-2 text-sm font-semibold">{topic.replaceAll("-", " ")}</h3><p className="mt-3 text-xs leading-5 text-[var(--muted)]">进入专题档案，当前尚未挂接完整证据和个股研究。</p></Link>)}</div></section>
  </ResearchShell>;
}
