import Link from "next/link";
import { ResearchShell } from "@/app/components/ResearchShell";
import theme from "@/content/research/themes/ai-technology.json";
import moduleIndex from "@/content/research/modules/index.json";
import catalog from "@/content/research/catalog.json";

export function generateStaticParams() { return catalog.themes.map((item) => ({ slug: item.id })); }

const topicNames: Record<string, string> = {
  "semiconductor-materials-and-equipment": "半导体材料与设备", "optical-materials-and-devices": "光学材料与器件", "pcb-and-thermal-materials": "PCB与热管理材料",
  "ai-chip-architecture": "AI芯片架构", "advanced-packaging": "先进封装", "hbm-and-high-bandwidth-memory": "HBM与高带宽存储", "enterprise-ssd": "企业级SSD",
  "800g-and-1-6t-optics": "800G与1.6T光互联", "thin-film-lithium-niobate": "薄膜铌酸锂", "high-speed-pcb-and-ccl": "高速PCB与CCL",
  "ai-data-center-power": "AI数据中心供电", "data-center-thermal-management": "数据中心热管理", "private-model-deployment": "私有模型部署"
};

const mainLines = [
  { name: "算力线", logic: "把模型训练与推理需求转成可交付的芯片、封装、加速卡和服务器。", moduleIds: ["materials-and-equipment", "compute-and-packaging"] },
  { name: "存储线", logic: "解决参数、数据和检查点的容量、带宽、时延与持续搬运。", moduleIds: ["storage-and-memory"] },
  { name: "互联线", logic: "解决大规模集群中服务器、交换机和芯片之间的数据交换瓶颈。", moduleIds: ["optical-interconnect", "switching-and-high-speed-connection"] },
  { name: "供电线", logic: "把电网能力转成高功率机柜可稳定使用的电源、UPS与热管理系统。", moduleIds: ["power-and-ups", "cooling-and-thermal-management"] },
  { name: "应用线", logic: "把数据、模型和推理能力转化为客户愿意持续付费的工作流和行业结果。", moduleIds: ["data-and-models", "models-inference-and-applications", "ops-and-security"] },
  { name: "承载线", logic: "提供PCB、材料、机房、集群集成和运营环境，让整套AI系统真正上线。", moduleIds: ["pcb-ccl-mlcc-and-glass-substrate", "data-center-infrastructure"] },
] as const;

const stockStatus = (stage: string) => stage === "专题已建立" ? "已建立映射" : "研究中";

export default async function ThemeDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const catalogTheme = catalog.themes.find((item) => item.id === slug);
  if (!catalogTheme) return null;
  if (slug !== theme.id) return <ResearchShell eyebrow="01 / INDUSTRY" title={catalogTheme.name} description={catalogTheme.summary}><div className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">板块 / 待建档</p><h2 className="mt-3 text-lg font-semibold">{catalogTheme.description}</h2></div><span className="research-tag">待建档</span></div><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">该板块的产业链、专题与个股研究尚未发布。</p><Link href="/themes" className="mt-5 inline-block text-xs font-semibold text-[var(--accent-dark)]">返回板块列表 →</Link></div></ResearchShell>;

  const topics = moduleIndex.items.flatMap((item) => item.topics.map((topic) => ({ topic, line: item.name })));
  const stocks = catalog.stocks.filter((stock) => stock.theme === slug);
  return <ResearchShell eyebrow="01 / INDUSTRY / AI TECHNOLOGY" title={theme.name} description={theme.thesis}>
    <div className="mt-4 border border-[var(--line)] bg-[var(--paper-strong)] p-4 text-xs leading-6 text-[var(--secondary)]"><b>板块状态：</b><span className="ml-1 inline-flex rounded border border-[var(--line)] px-2 py-1 text-[var(--accent-dark)]">已发布</span><b className="ml-3">截至：</b>{theme.evidence.asOf}。<b className="ml-3">数据：</b>{theme.evidence.qualityStatus}，不直接构成交易信号。</div>
    <section className="mt-8 grid gap-3 md:grid-cols-2"><article className="dashboard-panel"><p className="section-label">产业链全景 / 需求线</p><h2 className="mt-2 text-lg font-semibold">客户为什么买</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{theme.architecture.demandDimension}</p></article><article className="dashboard-panel"><p className="section-label">产业链全景 / 制造线</p><h2 className="mt-2 text-lg font-semibold">价值如何兑现</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{theme.architecture.manufacturingDimension}</p></article></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">产业链全景 / 双向对照</p><h2 className="mt-2 text-lg font-semibold">需求线与制造线：逐层对照</h2><p className="mt-3 text-xs leading-6 text-[var(--muted)]">需求线从客户结果向基础设施传导；制造线从材料设备向可交付系统汇聚。两侧通过工作负载和系统瓶颈发生映射。</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><div className="mb-3 flex items-center justify-between"><p className="section-label text-[var(--accent-dark)]">需求线 / D9 → D1</p><span className="text-[10px] text-[var(--muted)]">客户到采购</span></div><div className="grid gap-2">{theme.demandLayers.map((layer) => <article key={layer.level} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3"><div className="flex items-start gap-3"><b className="min-w-7 text-xs text-[var(--accent-dark)]">{layer.level}</b><div><h3 className="text-sm font-semibold">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--secondary)]">{layer.logic}</p><div className="mt-2 flex flex-wrap gap-1">{layer.nodes.map((node) => <span key={node} className="rounded border border-[var(--line)] px-2 py-1 text-[10px] text-[var(--muted)]">{node}</span>)}</div></div></div></article>)}</div></div><div><div className="mb-3 flex items-center justify-between"><p className="section-label text-[var(--accent-dark)]">制造线 / M1 → M9</p><span className="text-[10px] text-[var(--muted)]">材料到系统</span></div><div className="grid gap-2">{theme.manufacturingLayers.map((layer) => <article key={layer.level} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3"><div className="flex items-start gap-3"><b className="min-w-7 text-xs text-[var(--accent-dark)]">{layer.level}</b><div><h3 className="text-sm font-semibold">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--secondary)]">{layer.logic}</p><div className="mt-2 flex flex-wrap gap-1">{layer.nodes.map((node) => <span key={node} className="rounded border border-[var(--line)] px-2 py-1 text-[10px] text-[var(--muted)]">{node}</span>)}</div></div></div></article>)}</div></div></div></section>
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">产业链条 / 六条主线</p><h2>从全景图进入研究主线</h2></div><span className="research-tag">研究中</span></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{mainLines.map((line) => <article key={line.name} className="dashboard-panel"><div className="flex items-start justify-between gap-3"><h3 className="text-base font-semibold">{line.name}</h3><span className="research-tag">研究中</span></div><p className="mt-3 text-xs leading-6 text-[var(--secondary)]">{line.logic}</p><div className="mt-4 grid gap-2 border-t border-[var(--line)] pt-3">{line.moduleIds.map((moduleId) => { const item = moduleIndex.items.find((module) => module.id === moduleId); if (!item) return null; return <Link key={moduleId} href={`/modules/${moduleId}`} className="text-xs font-semibold text-[var(--accent-dark)]">{item.name} →</Link>; })}</div></article>)}</div></section>
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">专题研究 / 下一层</p><h2>该板块下的专题</h2></div><Link href="/topics">查看全部专题 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-3">{topics.map(({ topic, line }) => <Link key={topic} href={`/topics/${topic}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-2"><p className="section-label">AI科技 / {line}</p><span className="research-tag">待研究</span></div><h3 className="mt-2 text-sm font-semibold">{topicNames[topic] ?? topic.replaceAll("-", " ")}</h3><p className="mt-3 text-xs leading-5 text-[var(--muted)]">当前为专题入口，尚未形成完整研究结论。</p></Link>)}</div></section>
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">个股研究 / 下一层</p><h2>该板块下的个股</h2></div><Link href="/stocks">查看全部个股 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{stocks.map((stock) => <Link key={stock.code} href={`/stocks/${stock.slug}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-3"><div><p className="section-label">{stock.line} / {topicNames[stock.topic] ?? stock.topic}</p><h3 className="mt-2 text-base font-semibold">{stock.name} <span className="text-xs font-normal text-[var(--muted)]">{stock.code}</span></h3></div><span className="research-tag">{stockStatus(stock.stage)}</span></div><p className="mt-3 text-xs leading-6 text-[var(--secondary)]">{stock.summary}</p><div className="mt-3 flex flex-wrap gap-2"><span className="research-tag">板块：{theme.name}</span><span className="research-tag">专题：{topicNames[stock.topic] ?? stock.topic}</span></div></Link>)}</div></section>
  </ResearchShell>;
}
