import Link from "next/link";
import { ResearchShell } from "@/app/components/ResearchShell";
import theme from "@/content/research/themes/ai-technology.json";
import moduleIndex from "@/content/research/modules/index.json";
import catalog from "@/content/research/catalog.json";

export function generateStaticParams() { return catalog.themes.map((item) => ({ slug: item.id })); }

const topicNames: Record<string, string> = {
  "semiconductor-materials-and-equipment": "半导体材料与设备", "optical-materials-and-devices": "光学材料与器件", "pcb-and-thermal-materials": "PCB与热管理材料",
  "ai-chip-architecture": "AI芯片架构", "advanced-packaging": "先进封装", "hbm-and-high-bandwidth-memory": "HBM与高带宽存储", "enterprise-ssd": "企业级SSD",
  "800g-and-1-6t-optics": "800G与1.6T光互联", "thin-film-lithium-niobate": "薄膜铌酸锂", "high-speed-pcb-and-ccl": "高速PCB与CCL",
  "ai-data-center-power": "AI数据中心供电", "data-center-thermal-management": "数据中心热管理", "private-model-deployment": "私有模型部署"
};

export default async function ThemeDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const catalogTheme = catalog.themes.find((item) => item.id === slug);
  if (!catalogTheme) return null;
  if (slug !== theme.id) return <ResearchShell eyebrow="01 / INDUSTRY" title={catalogTheme.name} description={catalogTheme.summary}><div className="mt-4 dashboard-panel"><p className="section-label">板块入口</p><h2 className="mt-3 text-lg font-semibold">{catalogTheme.description}</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">该板块的专题与个股研究尚在整理，发布后会在此处按父级关系展示。</p><Link href="/themes" className="mt-5 inline-block text-xs font-semibold text-[var(--accent-dark)]">返回板块列表 →</Link></div></ResearchShell>;

  const topics = moduleIndex.items.flatMap((item) => item.topics.map((topic) => ({ topic, line: item.name })));
  const stocks = catalog.stocks.filter((stock) => stock.theme === slug);
  return <ResearchShell eyebrow="01 / INDUSTRY / AI TECHNOLOGY" title={theme.name} description={theme.thesis}>
    <div className="mt-4 border border-[var(--line)] bg-[var(--paper-strong)] p-4 text-xs leading-6 text-[var(--secondary)]"><b>板块状态：</b>{theme.researchStage}。<b className="ml-3">截至：</b>{theme.evidence.asOf}。<b className="ml-3">数据：</b>{theme.evidence.qualityStatus}，不直接构成交易信号。</div>
    <section className="mt-8 grid gap-3 md:grid-cols-2"><article className="dashboard-panel"><p className="section-label">DEMAND DIMENSION</p><h2 className="mt-2 text-lg font-semibold">需求传导：客户为什么要买</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{theme.architecture.demandDimension}</p></article><article className="dashboard-panel"><p className="section-label">MANUFACTURING DIMENSION</p><h2 className="mt-2 text-lg font-semibold">制造拆解：价值如何兑现</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{theme.architecture.manufacturingDimension}</p></article></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">BIDIRECTIONAL PANORAMA</p><h2 className="mt-2 text-lg font-semibold">需求线与制造线：逐层对照</h2><p className="mt-3 text-xs leading-6 text-[var(--muted)]">需求线从客户结果向基础设施传导；制造线从材料设备向可交付系统汇聚。两侧通过工作负载和系统瓶颈发生映射。</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><div className="mb-3 flex items-center justify-between"><p className="section-label text-[var(--accent-dark)]">DEMAND LINE / D9 → D1</p><span className="text-[10px] text-[var(--muted)]">客户到采购</span></div><div className="grid gap-2">{theme.demandLayers.map((layer) => <article key={layer.level} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3"><div className="flex items-start gap-3"><b className="min-w-7 text-xs text-[var(--accent-dark)]">{layer.level}</b><div><h3 className="text-sm font-semibold">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--secondary)]">{layer.logic}</p><div className="mt-2 flex flex-wrap gap-1">{layer.nodes.map((node) => <span key={node} className="rounded border border-[var(--line)] px-2 py-1 text-[10px] text-[var(--muted)]">{node}</span>)}</div></div></div></article>)}</div></div><div><div className="mb-3 flex items-center justify-between"><p className="section-label text-[var(--accent-dark)]">MANUFACTURING LINE / M1 → M9</p><span className="text-[10px] text-[var(--muted)]">材料到系统</span></div><div className="grid gap-2">{theme.manufacturingLayers.map((layer) => <article key={layer.level} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3"><div className="flex items-start gap-3"><b className="min-w-7 text-xs text-[var(--accent-dark)]">{layer.level}</b><div><h3 className="text-sm font-semibold">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--secondary)]">{layer.logic}</p><div className="mt-2 flex flex-wrap gap-1">{layer.nodes.map((node) => <span key={node} className="rounded border border-[var(--line)] px-2 py-1 text-[10px] text-[var(--muted)]">{node}</span>)}</div></div></div></article>)}</div></div></div></section>
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">TOPIC RESEARCH / CHILDREN</p><h2>该板块下的专题</h2></div><Link href="/topics">查看全部专题 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-3">{topics.map(({ topic, line }) => <Link key={topic} href={`/topics/${topic}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><p className="section-label">AI科技 / {line}</p><h3 className="mt-2 text-sm font-semibold">{topicNames[topic] ?? topic.replaceAll("-", " ")}</h3><p className="mt-3 text-xs leading-5 text-[var(--muted)]">进入专题，查看业务逻辑、技术路线与关联个股。</p></Link>)}</div></section>
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">EQUITY RESEARCH / CHILDREN</p><h2>该板块下的个股</h2></div><Link href="/stocks">查看全部个股 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{stocks.map((stock) => <Link key={stock.code} href={`/stocks/${stock.slug}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-3"><div><p className="section-label">{stock.line} / {topicNames[stock.topic] ?? stock.topic}</p><h3 className="mt-2 text-base font-semibold">{stock.name} <span className="text-xs font-normal text-[var(--muted)]">{stock.code}</span></h3></div><span className="text-xs text-[var(--accent-dark)]">进入 →</span></div><p className="mt-3 text-xs leading-6 text-[var(--secondary)]">{stock.summary}</p><div className="mt-3 flex flex-wrap gap-2"><span className="research-tag">板块：{theme.name}</span><span className="research-tag">状态：{stock.stage}</span></div></Link>)}</div></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">PUBLIC ARTICLE</p><h2 className="mt-2 text-lg font-semibold">AI全产业链分层详解</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">按算力线、存储线、互联线、供电线、应用线、承载线，从原材料、芯片、服务器、数据中心到模型和AI应用展开。</p><Link href="/reports/20260822-ai-industry-value-chain-panorama-v3.html" className="mt-4 inline-block text-xs font-semibold text-[var(--accent-dark)]">阅读产业链专题 →</Link></section>
  </ResearchShell>;
}
