import Link from "next/link";
import { ResearchShell } from "@/app/components/ResearchShell";
import theme from "@/content/research/themes/ai-technology.json";
import moduleIndex from "@/content/research/modules/index.json";

export function generateStaticParams() { return [{ slug: theme.id }]; }

export default async function ThemeDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug !== theme.id) return null;
  return <ResearchShell eyebrow="01 / INDUSTRY / AI TECHNOLOGY" title={theme.name} description={theme.thesis}>
    <div className="mt-4 border border-[var(--line)] bg-[var(--paper-strong)] p-4 text-xs leading-6 text-[var(--secondary)]"><b>状态：</b>{theme.researchStage}。<b className="ml-3">截至：</b>{theme.evidence.asOf}。<b className="ml-3">数据：</b>{theme.evidence.qualityStatus}，不直接构成交易信号。</div>
    <section className="mt-8 grid gap-3 md:grid-cols-2"><article className="dashboard-panel"><p className="section-label">DEMAND DIMENSION</p><h2 className="mt-2 text-lg font-semibold">需求传导：客户为什么要买</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{theme.architecture.demandDimension}</p><p className="mt-4 border-l-2 border-[var(--accent)] pl-3 text-xs leading-6">从终端应用、工作负载和部署方式反推系统采购，避免只看某个零部件的概念热度。</p></article><article className="dashboard-panel"><p className="section-label">MANUFACTURING DIMENSION</p><h2 className="mt-2 text-lg font-semibold">制造拆解：价值如何兑现</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">{theme.architecture.manufacturingDimension}</p><p className="mt-4 border-l-2 border-[var(--accent)] pl-3 text-xs leading-6">从材料、设备、工艺到部件和系统，追踪技术壁垒、供给瓶颈和利润传导。</p></article></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">BIDIRECTIONAL PANORAMA</p><h2 className="mt-2 text-lg font-semibold">需求线与制造线：逐层对照</h2><p className="mt-3 text-xs leading-6 text-[var(--muted)]">左侧从客户结果向基础设施传导；右侧从材料设备向可交付系统汇聚。两侧不是一条简单的上下游名单，而是通过工作负载和系统瓶颈发生映射。</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><div className="mb-3 flex items-center justify-between"><p className="section-label text-[var(--accent-dark)]">DEMAND LINE / D9 → D1</p><span className="text-[10px] text-[var(--muted)]">客户到采购</span></div><div className="grid gap-2">{theme.demandLayers.map((layer) => <article key={layer.level} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3"><div className="flex items-start gap-3"><b className="min-w-7 text-xs text-[var(--accent-dark)]">{layer.level}</b><div><h3 className="text-sm font-semibold">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--secondary)]">{layer.logic}</p><div className="mt-2 flex flex-wrap gap-1">{layer.nodes.map((node) => <span key={node} className="rounded border border-[var(--line)] px-2 py-1 text-[10px] text-[var(--muted)]">{node}</span>)}</div></div></div></article>)}</div></div><div><div className="mb-3 flex items-center justify-between"><p className="section-label text-[var(--accent-dark)]">MANUFACTURING LINE / M1 → M9</p><span className="text-[10px] text-[var(--muted)]">材料到系统</span></div><div className="grid gap-2">{theme.manufacturingLayers.map((layer) => <article key={layer.level} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-3"><div className="flex items-start gap-3"><b className="min-w-7 text-xs text-[var(--accent-dark)]">{layer.level}</b><div><h3 className="text-sm font-semibold">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--secondary)]">{layer.logic}</p><div className="mt-2 flex flex-wrap gap-1">{layer.nodes.map((node) => <span key={node} className="rounded border border-[var(--line)] px-2 py-1 text-[10px] text-[var(--muted)]">{node}</span>)}</div></div></div></article>)}</div></div></div></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">MEETING NODES</p><h2 className="mt-2 text-lg font-semibold">两条路径汇合的可交付节点</h2><div className="mt-5 grid gap-2 md:grid-cols-5">{theme.crossLinks.map((link) => <article key={link.meeting} className="border border-[var(--line)] bg-[#f4f1e9] p-3"><h3 className="text-sm font-semibold">{link.meeting}</h3><p className="mt-2 text-[10px] leading-5 text-[var(--muted)]">需求：{link.demand.join(" · ")}</p><p className="mt-1 text-[10px] leading-5 text-[var(--muted)]">制造：{link.manufacturing.join(" · ")}</p></article>)}</div><p className="mt-4 border-l-2 border-[var(--accent)] pl-3 text-xs leading-6">可用算力 = 芯片性能 × 网络效率 × 存储吞吐 × 供电散热可靠性 × 软件利用率。只有节点最终形成可部署、可调度、可计费能力，产业需求才真正闭环。</p></section>
    <section className="mt-8"><div className="panel-heading"><div><p className="section-label">VALUE MODULES</p><h2>模块入口</h2></div><Link href="/modules">模块总表 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{moduleIndex.items.map((item) => <Link key={item.id} href={`/modules/${item.id}`} className="border border-[var(--line)] bg-[rgba(250,248,243,.62)] p-4 transition hover:border-[var(--accent)]"><p className="section-label">{item.id}</p><h3 className="mt-2 font-semibold">{item.name}</h3><p className="mt-2 text-xs leading-6 text-[var(--secondary)]">{item.short}</p><p className="mt-3 text-xs leading-5"><b>瓶颈：</b>{item.bottleneck}</p></Link>)}</div></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">RESEARCH RULES</p><h2 className="mt-2 text-lg font-semibold">后续专题与个股如何挂接</h2><ul className="compact-list">{theme.researchQuestions.map((question) => <li key={question}><span>{question}</span></li>)}</ul><div className="mt-5 grid gap-2 md:grid-cols-2">{theme.coreRisks.map((risk) => <p key={risk} className="border border-[var(--line)] p-3 text-xs leading-5 text-[var(--secondary)]">风险：{risk}</p>)}</div><p className="mt-4 text-xs leading-6 text-[var(--muted)]">当前公司档案尚未在本次板块更新中发布。下一步按模块建立专题，再将经过身份、业务和时点证据校验的个股挂到专题下。</p></section>
    <section className="mt-8 dashboard-panel"><p className="section-label">PANORAMA / V0.3</p><h2 className="mt-2 text-lg font-semibold">AI全产业链分层详解</h2><p className="mt-3 text-sm leading-7 text-[var(--secondary)]">按算力线、存储线、互联线、供电线、应用线、承载线，从原材料、芯片、服务器、数据中心到模型和AI应用展开；CUDA归入算力平台底座，EDA归入芯片设计工具。</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/reports/20260822-ai-industry-value-chain-panorama-v3.html" className="inline-flex border border-[var(--accent)] bg-[var(--accent)] px-3 py-2 text-xs text-white hover:opacity-90">阅读最终专题 →</Link><Link href="/research/ai-hardware" className="inline-flex border border-[var(--line)] px-3 py-2 text-xs text-[var(--accent-dark)] hover:border-[var(--accent)]">查看技术细化页 →</Link></div></section>
  </ResearchShell>;
}
