import Link from "next/link";
import { ResearchShell } from "@/app/components/ResearchShell";
import { mechanisms } from "./mechanisms";

export default function StrategyMechanismsPage() {
  return <ResearchShell eyebrow="STRATEGY LIBRARY / MECHANISMS" title="交易机制" description="温度计机制负责门控，四套低位金叉策略独立运行；这里保存规则、源代码、参数和回测证据。">
    <section className="strategy-callout"><div><p className="section-label">运行模型</p><h2>选择一套，单独运行。</h2><p>四套策略不是逐层执行的漏斗。L2/L3 只是在规则上共享条件，日常运行时无需先跑其他策略；同时运行多个策略，仅用于回测比较和归因。</p></div><div className="strategy-badges"><span>独立运行</span><span>不自动交易</span></div></section>
    <section className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">SOURCE PACKAGE</p><h2>源代码与说明</h2></div><p>公开可读 / 可下载</p></div><div className="mt-4 grid gap-3 md:grid-cols-2"><a className="library-card" href="/strategy-source/low-cross-window-v1/README.md"><span>说明文档</span><h3>README.md</h3><p>四套策略的目标、边界、运行方式与验证产物。</p><i>查看 →</i></a><a className="library-card" href="/strategy-source/low-cross-window-v1/registry.json"><span>规则注册表</span><h3>registry.json</h3><p>固定策略 ID、硬条件、数据口径与 independent_select_one 运行模型。</p><i>查看 →</i></a><a className="library-card" href="/strategy-source/low-cross-window-v1/run_walkforward.py"><span>回测源码</span><h3>run_walkforward.py</h3><p>历史滚动回测、信号标注和四套策略标签逻辑。</p><i>查看 →</i></a><a className="library-card" href="/strategy-source/low-cross-window-v1/run_current_scan.py"><span>当日扫描源码</span><h3>run_current_scan.py</h3><p>按最新收盘和资金流运行四套独立策略的扫描程序。</p><i>查看 →</i></a></div></section>
    <section className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">MECHANISM INDEX</p><h2>温度计机制与四套策略</h2></div><p>点击查看单套规则</p></div><div className="mt-4 grid gap-3 md:grid-cols-2">{mechanisms.map((item) => <Link href={`/strategies/mechanisms/${item.id}`} className="library-card" key={item.id}><span>{item.id}</span><h3>{item.name}</h3><p>{item.short}</p><p className="mt-3 text-xs text-[var(--muted)]">{item.runtime}</p><i>查看机制 →</i></Link>)}</div></section>
    <section className="mt-4 dashboard-panel"><div className="panel-heading"><div><p className="section-label">BACKTEST EVIDENCE</p><h2>历史回测</h2></div><Link href="/strategies/outputs/20260831T224529-low-cross-window-v1" className="text-xs font-semibold text-[var(--accent-dark)]">查看最新结果 →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="metric"><p className="section-label">L1 纯形态</p><p className="mt-3 text-xl font-semibold">9,266</p><p className="mt-2 text-xs text-[var(--muted)]">10日胜率 48.13%</p></div><div className="metric"><p className="section-label">L2 基准</p><p className="mt-3 text-xl font-semibold">248</p><p className="mt-2 text-xs text-[var(--muted)]">10日均值 +2.887%</p></div><div className="metric"><p className="section-label">L3 增强</p><p className="mt-3 text-xl font-semibold">76</p><p className="mt-2 text-xs text-[var(--muted)]">10日胜率 69.74%</p></div></div></section>
  </ResearchShell>;
}
